/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.ue.gui;

import co.edu.ue.entities.Productos;
import co.edu.ue.model.ProductosDao;

/**
 *
 * @author Diana
 */
public class DetalleProductoFr extends javax.swing.JFrame {

    /**
     * Creates new form DetalleProductoFr
     */
    public DetalleProductoFr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDetalleProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblPago = new javax.swing.JLabel();
        lblNombreProducto1 = new javax.swing.JLabel();
        lblPrecio1 = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        lblProveedor1 = new javax.swing.JLabel();
        lblPago1 = new javax.swing.JLabel();
        lblNombreProducto2 = new javax.swing.JLabel();
        lblPrecio2 = new javax.swing.JLabel();
        lblCantidad2 = new javax.swing.JLabel();
        lblProveedor2 = new javax.swing.JLabel();
        lblPago2 = new javax.swing.JLabel();
        lblNombreProducto3 = new javax.swing.JLabel();
        lblPrecio3 = new javax.swing.JLabel();
        lblCantidad3 = new javax.swing.JLabel();
        lblProveedor3 = new javax.swing.JLabel();
        lblPago3 = new javax.swing.JLabel();
        lblNombreProducto4 = new javax.swing.JLabel();
        lblPrecio4 = new javax.swing.JLabel();
        lblCantidad4 = new javax.swing.JLabel();
        lblProveedor4 = new javax.swing.JLabel();
        lblPago4 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDetalleProducto.setText("Datos del Producto a agregar");

        lblNombreProducto.setText("Nombre Producto");

        lblPrecio.setText("Precio");

        lblCantidad.setText("Cantidad");

        lblProveedor.setText("Proveedor");

        lblPago.setText("Pago");

        lblPrecio1.setText("jLabel8");

        lblCantidad1.setText("jLabel9");

        lblProveedor1.setText("jLabel10");

        lblPago1.setText("jLabel11");

        lblNombreProducto2.setText("jLabel12");

        lblPrecio2.setText("jLabel13");

        lblCantidad2.setText("jLabel14");

        lblProveedor2.setText("jLabel15");

        lblPago2.setText("jLabel16");

        lblNombreProducto3.setText("jLabel17");

        lblPrecio3.setText("jLabel18");

        lblCantidad3.setText("jLabel19");

        lblProveedor3.setText("jLabel20");

        lblPago3.setText("jLabel21");

        lblNombreProducto4.setText("jLabel22");

        lblPrecio4.setText("jLabel23");

        lblCantidad4.setText("jLabel24");

        lblProveedor4.setText("jLabel25");

        lblPago4.setText("jLabel26");

        btnAgregarProducto.setText("Agregar Otro Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetalleProducto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarProducto)
                                .addGap(48, 48, 48)
                                .addComponent(btnActualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblNombreProducto)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblNombreProducto3)
                                                .addComponent(lblNombreProducto2)
                                                .addComponent(lblNombreProducto4))
                                            .addGap(59, 59, 59)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblNombreProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecio)
                                    .addComponent(lblPrecio1)
                                    .addComponent(lblPrecio2)
                                    .addComponent(lblPrecio3)
                                    .addComponent(lblPrecio4))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidad3)
                                    .addComponent(lblCantidad1)
                                    .addComponent(lblCantidad)
                                    .addComponent(lblCantidad2)
                                    .addComponent(lblCantidad4))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProveedor)
                                        .addGap(74, 74, 74)
                                        .addComponent(lblPago))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblProveedor4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPago4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblProveedor3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPago3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblProveedor2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPago2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblProveedor1)
                                            .addGap(77, 77, 77)
                                            .addComponent(lblPago1)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnLimpiar)
                                .addGap(66, 66, 66)
                                .addComponent(btnCerrar)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblDetalleProducto)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto)
                    .addComponent(lblPrecio)
                    .addComponent(lblCantidad)
                    .addComponent(lblProveedor)
                    .addComponent(lblPago))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrecio1)
                        .addComponent(lblCantidad1)
                        .addComponent(lblProveedor1)
                        .addComponent(lblPago1))
                    .addComponent(lblNombreProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto2)
                    .addComponent(lblPrecio2)
                    .addComponent(lblCantidad2)
                    .addComponent(lblProveedor2)
                    .addComponent(lblPago2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto3)
                    .addComponent(lblPrecio3)
                    .addComponent(lblCantidad3)
                    .addComponent(lblProveedor3)
                    .addComponent(lblPago3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto4)
                    .addComponent(lblPrecio4)
                    .addComponent(lblCantidad4)
                    .addComponent(lblProveedor4)
                    .addComponent(lblPago4))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar)
                    .addComponent(btnCerrar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        Productos productos = new Productos(lblNombreProducto1.getText(),lblNombreProducto2.getText(),
                        lblNombreProducto3.getText(),lblNombreProducto4.getText(),
                        lblPrecio1.getText(),lblPrecio2.getText(),lblPrecio3.getText(),lblPrecio4.getText(),
                        lblCantidad1.getText(),lblCantidad2.getText(),lblCantidad3.getText(),lblCantidad4.getText(),
                        lblProveedor1.getText(),lblProveedor2.getText(),lblProveedor3.getText(),lblProveedor4.getText(),
                        lblPago1.getText(),lblPago2.getText(),lblPago3.getText(),lblPago4.getText());
        ProductosDao dao1 = new ProductosDao();
        dao1.addUser(productos);
        cleanFields();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleProductoFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleProductoFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleProductoFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleProductoFr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleProductoFr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblCantidad2;
    private javax.swing.JLabel lblCantidad3;
    private javax.swing.JLabel lblCantidad4;
    private javax.swing.JLabel lblDetalleProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreProducto1;
    private javax.swing.JLabel lblNombreProducto2;
    private javax.swing.JLabel lblNombreProducto3;
    private javax.swing.JLabel lblNombreProducto4;
    private javax.swing.JLabel lblPago;
    private javax.swing.JLabel lblPago1;
    private javax.swing.JLabel lblPago2;
    private javax.swing.JLabel lblPago3;
    private javax.swing.JLabel lblPago4;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblPrecio3;
    private javax.swing.JLabel lblPrecio4;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblProveedor1;
    private javax.swing.JLabel lblProveedor2;
    private javax.swing.JLabel lblProveedor3;
    private javax.swing.JLabel lblProveedor4;
    // End of variables declaration//GEN-END:variables

    private void cleanFields() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
